print('crie um algoritimo que leia um numero e mostre seu dobro seu triplo e sua rais quadrada!')
n = int(input('digite um numero!'))
d = int(n * 2)
t = int(n * 3)
r = (n ** (1/2))
print('você digitou o numero {} seu dobro é {} e seu triplo é {} e sua raiz quadrada é \033[31;46m{}\033[m!'.format(n, d, t, r))
